name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Build and test with Rake
      run: |
        sudo apt-get install libsqlite3-dev
        sudo apt-get install libpq-dev
        sudo apt autoremove
        gem install bundler
        gem install sqlite3
        bundle install --jobs 4 --retry 3
        rails db:migrate RAILS_ENV=test
        bundle exec rake
